// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataitem.proto

//package main
package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataItem struct {
	OddA                 int64    `protobuf:"varint,1,opt,name=oddA,proto3" json:"oddA,omitempty"`
	EvenA                int64    `protobuf:"varint,2,opt,name=evenA,proto3" json:"evenA,omitempty"`
	OddB                 int32    `protobuf:"varint,3,opt,name=oddB,proto3" json:"oddB,omitempty"`
	EvenB                int32    `protobuf:"varint,4,opt,name=evenB,proto3" json:"evenB,omitempty"`
	Small                float32  `protobuf:"fixed32,5,opt,name=small,proto3" json:"small,omitempty"`
	Big                  float32  `protobuf:"fixed32,6,opt,name=big,proto3" json:"big,omitempty"`
	Short                string   `protobuf:"bytes,7,opt,name=short,proto3" json:"short,omitempty"`
	Long                 string   `protobuf:"bytes,8,opt,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataItem) Reset()         { *m = DataItem{} }
func (m *DataItem) String() string { return proto.CompactTextString(m) }
func (*DataItem) ProtoMessage()    {}
func (*DataItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_200f1ed4ce720214, []int{0}
}

func (m *DataItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataItem.Unmarshal(m, b)
}
func (m *DataItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataItem.Marshal(b, m, deterministic)
}
func (m *DataItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataItem.Merge(m, src)
}
func (m *DataItem) XXX_Size() int {
	return xxx_messageInfo_DataItem.Size(m)
}
func (m *DataItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DataItem.DiscardUnknown(m)
}

var xxx_messageInfo_DataItem proto.InternalMessageInfo

func (m *DataItem) GetOddA() int64 {
	if m != nil {
		return m.OddA
	}
	return 0
}

func (m *DataItem) GetEvenA() int64 {
	if m != nil {
		return m.EvenA
	}
	return 0
}

func (m *DataItem) GetOddB() int32 {
	if m != nil {
		return m.OddB
	}
	return 0
}

func (m *DataItem) GetEvenB() int32 {
	if m != nil {
		return m.EvenB
	}
	return 0
}

func (m *DataItem) GetSmall() float32 {
	if m != nil {
		return m.Small
	}
	return 0
}

func (m *DataItem) GetBig() float32 {
	if m != nil {
		return m.Big
	}
	return 0
}

func (m *DataItem) GetShort() string {
	if m != nil {
		return m.Short
	}
	return ""
}

func (m *DataItem) GetLong() string {
	if m != nil {
		return m.Long
	}
	return ""
}

func init() {
	proto.RegisterType((*DataItem)(nil), "main.DataItem")
}

func init() { proto.RegisterFile("dataitem.proto", fileDescriptor_200f1ed4ce720214) }

var fileDescriptor_200f1ed4ce720214 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xbf, 0x0a, 0xc2, 0x30,
	0x10, 0x87, 0xb9, 0xfe, 0xb3, 0x66, 0x10, 0x09, 0x0e, 0x37, 0x06, 0xa7, 0x4c, 0x2e, 0x3e, 0x41,
	0x8b, 0x8b, 0x6b, 0xdf, 0xe0, 0x4a, 0x43, 0x2d, 0x34, 0x89, 0xd4, 0xc3, 0xe7, 0xf2, 0x11, 0x25,
	0x17, 0xdd, 0x7e, 0xdf, 0xc7, 0x07, 0x77, 0xea, 0x30, 0x11, 0xd3, 0xc2, 0xce, 0x5f, 0x9e, 0x5b,
	0xe4, 0xa8, 0x2b, 0x4f, 0x4b, 0x38, 0x7f, 0x40, 0xb5, 0x37, 0x62, 0xba, 0xb3, 0xf3, 0x5a, 0xab,
	0x2a, 0x4e, 0x53, 0x87, 0x60, 0xc0, 0x96, 0x83, 0x6c, 0x7d, 0x52, 0xb5, 0x7b, 0xbb, 0xd0, 0x61,
	0x21, 0x32, 0xc3, 0xaf, 0xec, 0xb1, 0x34, 0x60, 0x6b, 0x29, 0xfb, 0x7f, 0xd9, 0x63, 0x25, 0x32,
	0x43, 0xb2, 0x2f, 0x4f, 0xeb, 0x8a, 0xb5, 0x01, 0x5b, 0x0c, 0x19, 0xf4, 0x51, 0x95, 0xe3, 0x32,
	0x63, 0x23, 0x2e, 0x4d, 0xe9, 0x1e, 0x71, 0x63, 0xdc, 0x19, 0xb0, 0xfb, 0x21, 0x43, 0xba, 0xb3,
	0xc6, 0x30, 0x63, 0x2b, 0x52, 0xf6, 0xd8, 0xc8, 0xff, 0xd7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2f, 0xe7, 0x2a, 0x9b, 0xd1, 0x00, 0x00, 0x00,
}
